.PHONY: clean All

All:
	@echo "----------Building project:[ FahrenheitCelsius - Debug ]----------"
	@$(MAKE) -f  "FahrenheitCelsius.mk"
clean:
	@echo "----------Cleaning project:[ FahrenheitCelsius - Debug ]----------"
	@$(MAKE) -f  "FahrenheitCelsius.mk" clean
